WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(m => m.ProductId == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RеmoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(m => m.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shipping)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("","Извините, ваша корзина пуста");

            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shipping);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shipping);
            }            
        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string type = null)
        {
            ViewBag.SelectedType = type;

            IEnumerable<string> types = repository.Products
                .Select(product => product.Type)
                .Distinct()
                .OrderBy(x => x);
            return PartialView("FlexMenu", types);
        }
    }
}

WebUI/Controllers/ProductsController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ProductsController : Controller
    {
        private IProductRepository repository;
        public ProductsController(IProductRepository repo)
        {
            repository = repo;
        }
        public int pageSize = 5;

        public ActionResult Search(string findWord, int page = 1)
        {
            if (!String.IsNullOrEmpty(findWord))
            {
                ViewBag.Word = findWord;
                findWord = findWord.ToUpper();
                ProductsListViewModel model = new ProductsListViewModel
                {
                Products = repository.Products
                .Where(s => s.Name.ToUpper().Contains(findWord) || s.Description.ToUpper().Contains(findWord) || s.Brand.ToUpper().Contains(findWord) || s.Type.ToUpper().Contains(findWord))
                .OrderBy(Product => Product.ProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = pageSize,
                        TotalItems = findWord == null ?
                        repository.Products.Count() :
                        repository.Products.Where(s => s.Name.ToUpper().Contains(findWord) || s.Description.ToUpper().Contains(findWord) || s.Brand.ToUpper().Contains(findWord) || s.Type.ToUpper().Contains(findWord)).Count()
                    }
                };
                return View(model);
            }
            return Redirect("/Products/List");
        }


        public ViewResult List(string type,int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(b => type == null || b.Type == type)
                .OrderBy(Product => Product.ProductId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = type == null ? 
                        repository.Products.Count() :                     
                        repository.Products.Where(product => product.Type == type).Count()
                },
                CurrentType = type
            };
            return View(model);
        }
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null; 
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.5.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-grid.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" />
    @RenderSection("scripts", required: false)
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container-fluid">
        <div class="navbar bg-dark navbar-dark" style="margin-bottom:20px;" role="navigation">
            <a class="navbar-brand" href="/">
                <div>
                    <div style="font-size: 1.5em">
                        <img src="~/Content/Image/ava.png" class="logo" alt="Logo" />
                        <div class="d-sm-inline d-none">AVTOзапчасть</></div>
                    </div>
                </div>
            </a>
            @using (Html.BeginForm("Search", "Products", FormMethod.Get, new { @class = "form-inline" }))
            {
                <p>
                    <input class="form-control" placeholder="Поиск" type="text" name="findWord" value="@ViewBag.Word" maxlength="50">
                    <input class="btn btn-success" type="submit" value="Найти" />
                </p>
            }
            @Html.Action("Summary", "Cart")
        </div>
        <div class="d-block d-md-none">
            @Html.Action("Menu", "Nav", new { horizontalNav = true })
        </div>
        <div class="row">
            <div id="genres" class="col-md-3 d-none d-md-block">
                @Html.Action("Menu", "Nav")
            </div>
            <div class="col-12 col-md-8">
                @RenderBody()
            </div>
        </div>
        <hr />
        <div class="navbar navbar-light" style=" margin-top: 20px;">            
            <div class="d-none d-sm-block col-lg-3"></div>
            <div class="col-9">
                <h3>Контакты:</h3>
            </div>
            <div class="d-none d-sm-block col-lg-3"></div>
            <div class="col-12 col-md-6 col-lg-3">
                <address>                    
                    <a href="https://wa.me/+77013596153">
                        <img src="~/Content/Image/whatsapp.png" width="40px" height="auto" /> 8 (701) 359 61 53<br />
                    </a>
                    <a href="https://wa.me/+77051883926">
                        <img src="~/Content/Image/whatsapp.png" width="40px" height="auto"/> 8 (705) 188 39 26<br />
                    </a>
                    <a href="https://wa.me/+77009278491">
                        <img src="~/Content/Image/whatsapp.png" width="40px" height="auto" /> 8 (700) 927 84 91
                    </a>
                </address>
            </div>
            <div class="col-12 col-md-6">
                <address>
                    <a href="https://www.instagram.com/avto_zapchast_2017/?utm_medium=copy_link"><img src="https://i.pinimg.com/originals/04/78/03/047803389003a5e9cdb22c7feffce512.png" width="37 px" height="auto" alt="instagram" /> avto_zapchast_2017<br /><br /></a>
                    <strong> Email:</strong>   <a href="mailto:avtozapchast2017@mail.ru">avtozapchast2017@mail.ru</a><br />
                    <strong>Наш адрес:</strong> Казахстан, г.Караганда, ул.Четская 16/1, AVTOзапчасть <br />
                </address>
            </div>
        </div>
    </div>
</body>
</html>

WebUI/Views/Shared/_ProductSummary.cshtml
@model Domain.Entities.Product

    
<div class="row">
    <div class="col-4 col-sm-5 col-xl-7">
        @if (Model.Image != null)
        {
        <div class="div-avatar">
            @Html.Raw("<img class=\"photoList\" src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(Model.Image) + "\" />")
        </div>
        }
    </div>
    <div class="col-8 col-sm-7 col-xl-5 text-right">
        <div class="col-12 col-lg-4 float-right">
            <div class="float-right font-weight-normal">
                <h5>
                    <strong id="price" style="height: 30px;" class="float-right badge-pill badge-dark">
                        @Model.Price.ToString("# Тг")
                    </strong>
                </h5>
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    <div class="float-right">
                        @Html.HiddenFor(x => x.ProductId)
                        @Html.Hidden("returnUrl", @Request.Url.PathAndQuery)
                        <input type="submit" class="btn badge-pill btn-success" value="В корзину" />
                    </div>
                }
            </div>
        </div>

        <div class="col-12 col-lg-8 float-right">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Brand</strong>
            </h4>
        </div>
    </div>
</div>
<span class="lead">@Model.Description</span>    
<hr />